### ISSUE TITLE
Symbolize or create shared style

### ISSUE THREAD

**Issue by lostmonster** [agisilaos/Iconinator-for-Sketch#6]
it would be cool if this plugin also either symbolized the objects so that changing them would push the change across all of the icons, if we wanted to visualize the changes on the spot, opposed to running the plugin again!

**Comment by agisilaos** [comment]
Hey @lostmonster, 

You can already do that, so let's say that you edit your original icon, if you use the plugin again it will update all the other sizes of the app icon with the new design, try it out and tell me what you think!

**Comment by agisilaos** [comment]
I will add this to my list for the next update. Yup, nose i understood what you said. Thanks for the suggestion @lostmonster
